pipeline:
  test:
    image: node:4.2
    commands:
    - make install
    - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-sftp
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: SFTP
  desc: Publish files and artifacts via SFTP
  type: publish
  image: plugins/drone-sftp
  labels:
    - sftp
    - server
